In [ ]:
import numpy as np
import pandas as pd

# 1. Preprocess your dataset. Indicate which steps worked and which didn’t. Include your thoughts on why certain steps worked and certain steps didn’t.

In [ ]:
#Loaded csv data from local
df_new = pd.read_csv('/Users/trimpu/Downloads/abalone.data')
#converted to a DataFrame
df_new1 = pd.DataFrame(df_new)
df_new1

#columns data from source "https://archive.ics.uci.edu/ml/datasets/Abalone"
Sex / nominal / -- / M, F, and I (infant)
Length / continuous / mm / Longest shell measurement
Diameter / continuous / mm / perpendicular to length
Height / continuous / mm / with meat in shell
Whole weight / continuous / grams / whole abalone
Shucked weight / continuous / grams / weight of meat
Viscera weight / continuous / grams / gut weight (after bleeding)
Shell weight / continuous / grams / after being dried
Rings / integer / -- / +1.5 gives the age in years

In [3]:
df_new1.columns = ['Sex', 'Length', 'Diameter', 'Height', 'Whole weight', 'Shucked weigth', 'Viscera weight', 'Shell weigth', 'Rings']
df_new1.head(2)

,Sex,Length,Diameter,Height,Whole weight,Shucked weigth,Viscera weight,Shell weigth,Rings
0,M,0.35,0.265,0.090,0.2255,0.0995,0.0485,0.07,7
1,F,0.53,0.420,0.135,0.6770,0.2565,0.1415,0.21,9

In [4]:
#Preprocess your dataset. Indicate which steps worked and which didn’t. Include your thoughts on why certain steps worked and certain steps didn’t. 
df_new1.isnull().sum()

Sex               0
Length            0
Diameter          0
Height            0
Whole weight      0
Shucked weigth    0
Viscera weight    0
Shell weigth      0
Rings             0
dtype: int64

In [5]:
df_new1.corr()

,Length,Diameter,Height,Whole weight,Shucked weigth,Viscera weight,Shell weigth,Rings
Length,1.000000,0.986813,0.827552,0.925255,0.897905,0.903010,0.897697,0.557123
Diameter,0.986813,1.000000,0.833705,0.925452,0.893159,0.899726,0.905328,0.575005
Height,0.827552,0.833705,1.000000,0.819209,0.774957,0.798293,0.817326,0.558109
Whole weight,0.925255,0.925452,0.819209,1.000000,0.969403,0.966372,0.955351,0.540818
Shucked weigth,0.897905,0.893159,0.774957,0.969403,1.000000,0.931956,0.882606,0.421256
Viscera weight,0.903010,0.899726,0.798293,0.966372,0.931956,1.000000,0.907647,0.504274
Shell weigth,0.897697,0.905328,0.817326,0.955351,0.882606,0.907647,1.000000,0.628031
Rings,0.557123,0.575005,0.558109,0.540818,0.421256,0.504274,0.628031,1.000000

In [6]:
#.describe() generates descriptive statistics that summarize the central tendency, dispersion and shape of a dataset’s distribution, excluding NaN values.
df_new1.describe()

,Length,Diameter,Height,Whole weight,Shucked weigth,Viscera weight,Shell weigth,Rings
count,4176.000000,4176.000000,4176.000000,4176.000000,4176.00000,4176.000000,4176.000000,4176.000000
mean,0.524009,0.407892,0.139527,0.828818,0.35940,0.180613,0.238852,9.932471
std,0.120103,0.099250,0.041826,0.490424,0.22198,0.109620,0.139213,3.223601
min,0.075000,0.055000,0.000000,0.002000,0.00100,0.000500,0.001500,1.000000
25%,0.450000,0.350000,0.115000,0.441500,0.18600,0.093375,0.130000,8.000000
50%,0.545000,0.425000,0.140000,0.799750,0.33600,0.171000,0.234000,9.000000
75%,0.615000,0.480000,0.165000,1.153250,0.50200,0.253000,0.329000,11.000000
max,0.815000,0.650000,1.130000,2.825500,1.48800,0.760000,1.005000,29.000000

In [7]:
#concise summary of a DataFrame.
df_new1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4176 entries, 0 to 4175
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Sex             4176 non-null   object
 1   Length          4176 non-null   float64
 2   Diameter        4176 non-null   float64
 3   Height          4176 non-null   float64
 4   Whole weight    4176 non-null   float64
 5   Shucked weigth  4176 non-null   float64
 6   Viscera weight  4176 non-null   float64
 7   Shell weigth    4176 non-null   float64
 8   Rings           4176 non-null   int64
dtypes: float64(7), int64(1), object(1)
memory usage: 293.8+ KB

In [8]:
df_new1['Sex'].unique()

array(['M', 'F', 'I'], dtype=object)

In [9]:
#converting categorical data into numerial
df_sex_onehot = pd.get_dummies(df_new1['Sex'])
df_new1 = df_new1.drop('Sex', axis=1)
df_new1 = df_new1.join(df_sex_onehot)
df_new1

,Length,Diameter,Height,Whole weight,Shucked weigth,Viscera weight,Shell weigth,Rings,F,I,M
0,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.0700,7,0,0,1
1,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.2100,9,1,0,0
2,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.1550,10,0,0,1
3,0.330,0.255,0.080,0.2050,0.0895,0.0395,0.0550,7,0,1,0
4,0.425,0.300,0.095,0.3515,0.1410,0.0775,0.1200,8,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...
4171,0.565,0.450,0.165,0.8870,0.3700,0.2390,0.2490,11,1,0,0
4172,0.590,0.440,0.135,0.9660,0.4390,0.2145,0.2605,10,0,0,1
4173,0.600,0.475,0.205,1.1760,0.5255,0.2875,0.3080,9,0,0,1
4174,0.625,0.485,0.150,1.0945,0.5310,0.2610,0.2960,10,1,0,0
4175,0.710,0.555,0.195,1.9485,0.9455,0.3765,0.4950,12,0,0,1

In [10]:
df_new1.dropna()
df_new1

,Length,Diameter,Height,Whole weight,Shucked weigth,Viscera weight,Shell weigth,Rings,F,I,M
0,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.0700,7,0,0,1
1,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.2100,9,1,0,0
2,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.1550,10,0,0,1
3,0.330,0.255,0.080,0.2050,0.0895,0.0395,0.0550,7,0,1,0
4,0.425,0.300,0.095,0.3515,0.1410,0.0775,0.1200,8,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...
4171,0.565,0.450,0.165,0.8870,0.3700,0.2390,0.2490,11,1,0,0
4172,0.590,0.440,0.135,0.9660,0.4390,0.2145,0.2605,10,0,0,1
4173,0.600,0.475,0.205,1.1760,0.5255,0.2875,0.3080,9,0,0,1
4174,0.625,0.485,0.150,1.0945,0.5310,0.2610,0.2960,10,1,0,0
4175,0.710,0.555,0.195,1.9485,0.9455,0.3765,0.4950,12,0,0,1

In [11]:
#Rings / integer / -- / +1.5 gives the age in years -- as per dataset
df_new1['Rings_year'] = df_new1['Rings']+1.5
df_new1

,Length,Diameter,Height,Whole weight,Shucked weigth,Viscera weight,Shell weigth,Rings,F,I,M,Rings_year
0,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.0700,7,0,0,1,8.5
1,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.2100,9,1,0,0,10.5
2,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.1550,10,0,0,1,11.5
3,0.330,0.255,0.080,0.2050,0.0895,0.0395,0.0550,7,0,1,0,8.5
4,0.425,0.300,0.095,0.3515,0.1410,0.0775,0.1200,8,0,1,0,9.5
...,...,...,...,...,...,...,...,...,...,...,...,...
4171,0.565,0.450,0.165,0.8870,0.3700,0.2390,0.2490,11,1,0,0,12.5
4172,0.590,0.440,0.135,0.9660,0.4390,0.2145,0.2605,10,0,0,1,11.5
4173,0.600,0.475,0.205,1.1760,0.5255,0.2875,0.3080,9,0,0,1,10.5
4174,0.625,0.485,0.150,1.0945,0.5310,0.2610,0.2960,10,1,0,0,11.5
4175,0.710,0.555,0.195,1.9485,0.9455,0.3765,0.4950,12,0,0,1,13.5

In [12]:
df_new1.corr()

,Length,Diameter,Height,Whole weight,Shucked weigth,Viscera weight,Shell weigth,Rings,F,I,M,Rings_year
Length,1.000000,0.986813,0.827552,0.925255,0.897905,0.903010,0.897697,0.557123,0.309602,-0.551613,0.236783,0.557123
Diameter,0.986813,1.000000,0.833705,0.925452,0.893159,0.899726,0.905328,0.575005,0.318581,-0.564431,0.240567,0.575005
Height,0.827552,0.833705,1.000000,0.819209,0.774957,0.798293,0.817326,0.558109,0.298306,-0.518828,0.215869,0.558109
Whole weight,0.925255,0.925452,0.819209,1.000000,0.969403,0.966372,0.955351,0.540818,0.299668,-0.557757,0.252305,0.540818
Shucked weigth,0.897905,0.893159,0.774957,0.969403,1.000000,0.931956,0.882606,0.421256,0.263919,-0.521995,0.252048,0.421256
Viscera weight,0.903010,0.899726,0.798293,0.966372,0.931956,1.000000,0.907647,0.504274,0.308363,-0.556267,0.242489,0.504274
Shell weigth,0.897697,0.905328,0.817326,0.955351,0.882606,0.907647,1.000000,0.628031,0.306248,-0.547116,0.235652,0.628031
Rings,0.557123,0.575005,0.558109,0.540818,0.421256,0.504274,0.628031,1.000000,0.250620,-0.435958,0.181426,1.000000
F,0.309602,0.318581,0.298306,0.299668,0.263919,0.308363,0.306248,0.250620,1.000000,-0.464461,-0.512449,0.250620
I,-0.551613,-0.564431,-0.518828,-0.557757,-0.521995,-0.556267,-0.547116,-0.435958,-0.464461,1.000000,-0.522462,-0.435958
M,0.236783,0.240567,0.215869,0.252305,0.252048,0.242489,0.235652,0.181426,-0.512449,-0.522462,1.000000,0.181426
Rings_year,0.557123,0.575005,0.558109,0.540818,0.421256,0.504274,0.628031,1.000000,0.250620,-0.435958,0.181426,1.000000

In [13]:
X = df_new1.drop(labels='Rings_year', axis=1)
y =df_new1['Rings_year']

# 2. Create a decision tree model tuned to the best of your abilities. Explain how you tuned it.

In [14]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error as MSE, r2_score

SEED=1
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=SEED)
dt = DecisionTreeRegressor(max_depth=4, min_samples_leaf=0.1, random_state=SEED)
dt.fit(X_train, y_train)
y_pred = dt.predict(X_test)
mse_dt = MSE(y_test, y_pred)
rmse_dt = mse_dt**(1/2)
rmse_dt
#mse_dt
r2_val = r2_score(y_test, y_pred)
r2_val

0.9116927702321547

In [15]:
import sys
import warnings
if not sys.warnoptions:
        warnings.simplefilter("ignore")

In [16]:
from sklearn.tree import DecisionTreeRegressor
SEED=2
dt = DecisionTreeRegressor(random_state=SEED)
from sklearn.model_selection import GridSearchCV
params_dt={'max_depth':[3,4,6],
          'min_samples_leaf': [0.1,0.12, 0.14, 0.16,0.18]}
grid_dt = GridSearchCV(estimator=dt, param_grid=params_dt, scoring='accuracy', cv=10, n_jobs=-1)
grid_dt.fit(X_train, y_train)
#from sklearn.metrics import roc_auc_score
best_hyperparams = grid_dt.best_params_
print("Best hyperparameters:{:.3f}", best_hyperparams)
best_model = grid_dt.best_estimator_
test_acc = best_model.score(X_test, y_test)
print('Test set accuracy score:{:.3f}'.format(test_acc))

Best hyperparameters:{:.3f} {'max_depth': 3, 'min_samples_leaf': 0.1}
Test set accuracy score:0.904

# 3. Create a random forest model tuned to the best of your abilities. Explain how you tuned it.

In [17]:
X = df_new1.drop(labels='Rings_year', axis=1)
y =df_new1['Rings_year']
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error as MSE, r2_score
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)
#rf = RandomForestRegressor(n_estimators=400, min_samples_leaf=0.1, random_state=1)
rf = RandomForestRegressor(max_depth=4,n_estimators=400, min_samples_leaf=0.1, random_state=1)
rf.fit(X_train, y_train)
y_pred = rf.predict(X_test)
mse_dt = MSE(y_test, y_pred)
rmse_dt = mse_dt**(1/2)
print(rmse_dt)
r2_val = r2_score(y_test, y_pred)
r2_val

1.3546377870554485

0.8094245733657386

In [18]:
from sklearn.ensemble import RandomForestRegressor
SEED=2
rf = RandomForestRegressor(random_state=SEED)
#instantiate rf's hyperparameters
rf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'criterion': 'mse',
 'max_depth': None,
 'max_features': 'auto',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_impurity_split': None,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': 2,
 'verbose': 0,
 'warm_start': False}

In [19]:
X = df_new1.drop(labels='Rings_year', axis=1)
y =df_new1['Rings_year']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)
from sklearn.metrics import mean_squared_error as MSE
from sklearn.model_selection import GridSearchCV
params_rf = {'n_estimators':[300,400,500], 
            'max_depth': [4,6,8], 
            'min_samples_leaf':[0.1,0.2], 
            'max_features':['log2', 'sqrt', 'auto']}
grid_rf = GridSearchCV(estimator=rf, param_grid=params_rf, cv=3, scoring='neg_mean_squared_error', verbose=1, n_jobs=-1)
grid_rf.fit(X_train, y_train)
best_hyperparams = grid_rf.best_params_
print('Best hyperparameters :{:.2f}', best_hyperparams)
best_model = grid_rf.best_estimator_
y_pred = best_model.predict(X_test)
rmse_test = MSE(y_test, y_pred)**(1/2)
print('Test set RMSE of rf:{:.2f}'.format(rmse_test))

Fitting 3 folds for each of 54 candidates, totalling 162 fits
Best hyperparameters :{:.2f} {'max_depth': 4, 'max_features': 'auto', 'min_samples_leaf': 0.1, 'n_estimators': 300}
Test set RMSE of rf:1.35

# 4. Create an xgboost model tuned to the best of your abilities. Explain how you tuned it.

In [20]:
import numpy as np
import pandas as pd
import xgboost as xg
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error as MSE, r2_score
X = df_new1.drop(labels='Rings_year', axis=1)
y =df_new1['Rings_year']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)
xg_dt = xg.XGBRegressor(n_estimators=300, max_depth=1, random_state=SEED)
xg_dt.fit(X_train, y_train)
y_pred=xg_dt.predict(X_test)
rmse_test = MSE(y_test, y_pred)**(1/2)
print('rmse:{:.2f}'.format(rmse_test))
r2_value = r2_score(y_test, y_pred)
r2_val

rmse:0.08

0.8094245733657386

# 5. Which model performed best? What is your performance metric? Why?

DecisionTreeRegressor performed best out of these three. RandomForestRegressor and XGBRegressor got the same performance values. 
Though the y parameters looks biased, as "Rings" and "Rings_year", both columns have the same correlation and it is biased to take both into consideration. 
Performance is dropped when "Rings_year" column is taken alone.  
So this dataset looks like a multilabel classification problem. Used LabelEncoder for "Sex" column and did multilabel classification.

In [51]:
import numpy as np
import pandas as pd
#Loaded csv data from local
df_new = pd.read_csv('/Users/trimpu/Downloads/abalone.data')
#converted to a DataFrame
df_new1 = pd.DataFrame(df_new)
df_new1

      M  0.455  0.365  0.095   0.514  0.2245   0.101    0.15  15
0     M  0.350  0.265  0.090  0.2255  0.0995  0.0485  0.0700   7
1     F  0.530  0.420  0.135  0.6770  0.2565  0.1415  0.2100   9
2     M  0.440  0.365  0.125  0.5160  0.2155  0.1140  0.1550  10
3     I  0.330  0.255  0.080  0.2050  0.0895  0.0395  0.0550   7
4     I  0.425  0.300  0.095  0.3515  0.1410  0.0775  0.1200   8
...  ..    ...    ...    ...     ...     ...     ...     ...  ..
4171  F  0.565  0.450  0.165  0.8870  0.3700  0.2390  0.2490  11
4172  M  0.590  0.440  0.135  0.9660  0.4390  0.2145  0.2605  10
4173  M  0.600  0.475  0.205  1.1760  0.5255  0.2875  0.3080   9
4174  F  0.625  0.485  0.150  1.0945  0.5310  0.2610  0.2960  10
4175  M  0.710  0.555  0.195  1.9485  0.9455  0.3765  0.4950  12

[4176 rows x 9 columns]

In [52]:
df_new1.columns = ['Sex', 'Length', 'Diameter', 'Height', 'Whole weight', 'Shucked weigth', 'Viscera weight', 'Shell weigth', 'Rings']
df_new1.head(2)

,Sex,Length,Diameter,Height,Whole weight,Shucked weigth,Viscera weight,Shell weigth,Rings
0,M,0.35,0.265,0.090,0.2255,0.0995,0.0485,0.07,7
1,F,0.53,0.420,0.135,0.6770,0.2565,0.1415,0.21,9

In [53]:
#Preprocess your dataset. Indicate which steps worked and which didn’t. Include your thoughts on why certain steps worked and certain steps didn’t. 
df_new1.isnull().sum()

Sex               0
Length            0
Diameter          0
Height            0
Whole weight      0
Shucked weigth    0
Viscera weight    0
Shell weigth      0
Rings             0
dtype: int64

In [41]:
df_new1['Sex'].unique()

array(['M', 'F', 'I'], dtype=object)

df_sex_onehot = pd.get_dummies(df_new1['Sex'])
df_new1 = df_new1.drop('Sex', axis=1)
df_new1 = df_new1.join(df_sex_onehot)
df_new1

In [54]:
#LabelEncoder improved accuracy instead of onehot encoding
from sklearn.preprocessing import LabelEncoder
LE = LabelEncoder()

In [67]:
df_new1['Label'] = LE.fit_transform(df_new1['Sex'])
df_new1.drop(labels = 'Sex', axis=1, inplace=True)
df_new1

,Length,Diameter,Height,Whole weight,Shucked weigth,Viscera weight,Shell weigth,Rings,Label
0,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.0700,7,2
1,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.2100,9,0
2,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.1550,10,2
3,0.330,0.255,0.080,0.2050,0.0895,0.0395,0.0550,7,1
4,0.425,0.300,0.095,0.3515,0.1410,0.0775,0.1200,8,1
...,...,...,...,...,...,...,...,...,...
4171,0.565,0.450,0.165,0.8870,0.3700,0.2390,0.2490,11,0
4172,0.590,0.440,0.135,0.9660,0.4390,0.2145,0.2605,10,2
4173,0.600,0.475,0.205,1.1760,0.5255,0.2875,0.3080,9,2
4174,0.625,0.485,0.150,1.0945,0.5310,0.2610,0.2960,10,0
4175,0.710,0.555,0.195,1.9485,0.9455,0.3765,0.4950,12,2

# DecisionTreeClassifier Tuning with GridSearchCV

In [68]:
from sklearn.model_selection import train_test_split
X = df_new1.drop(labels='Label', axis=1)
y =df_new1['Label']
SEED=1
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=SEED)
from sklearn.tree import DecisionTreeClassifier
SEED=1
dt = DecisionTreeClassifier(random_state=SEED)
print(dt.get_params())

{'ccp_alpha': 0.0, 'class_weight': None, 'criterion': 'gini', 'max_depth': None, 'max_features': None, 'max_leaf_nodes': None, 'min_impurity_decrease': 0.0, 'min_impurity_split': None, 'min_samples_leaf': 1, 'min_samples_split': 2, 'min_weight_fraction_leaf': 0.0, 'random_state': 1, 'splitter': 'best'}

In [69]:
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import confusion_matrix, classification_report
params_dt = {'max_depth': [3,4,5], 
            'min_samples_leaf': [0.4, 0.06, 0.08], 
            'max_features':[0.2,0.4,0.6,0.8]}
grid_dt = GridSearchCV(estimator=dt, param_grid=params_dt, scoring='accuracy', cv=10, n_jobs=-1)
grid_dt.fit(X_train, y_train)
best_hyperparameters = grid_dt.best_params_
print('Best hyperparameters :\n', best_hyperparameters)
best_cv_score = grid_dt.best_score_
print('Best cv accuracy :{:.3f}'.format(best_cv_score))
best_model = grid_dt.best_estimator_
test_acc = best_model.score(X_test, y_test)
print('Test set accuracy of best model:{:.3f}'.format(test_acc))
y_pred = grid_dt.predict(X_test)
print(classification_report(y_test, y_pred))

Best hyperparameters :
 {'max_depth': 4, 'max_features': 0.2, 'min_samples_leaf': 0.06}
Best cv accuracy :0.540
Test set accuracy of best model:0.531
              precision    recall  f1-score   support

           0       0.46      0.10      0.16       265
           1       0.80      0.67      0.73       277
           2       0.42      0.79      0.55       294

    accuracy                           0.53       836
   macro avg       0.56      0.52      0.48       836
weighted avg       0.56      0.53      0.49       836

# RandomForestClassifier Tuning with GridSearchCV

In [70]:
from sklearn.model_selection import train_test_split
X = df_new1.drop(labels='Label', axis=1)
y =df_new1['Label']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=SEED)
from sklearn.ensemble import RandomForestClassifier
SEED=3
rf = RandomForestClassifier(random_state=SEED)
rf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'auto',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_impurity_split': None,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': 3,
 'verbose': 0,
 'warm_start': False}

In [71]:
from sklearn.metrics import mean_squared_error as MSE
from sklearn.model_selection import GridSearchCV
params_df = {'n_estimators': [300,400,500], 
            'max_depth': [4,6,8], 
            'min_samples_leaf':[0.1, 0.2, 0.3], 
            'max_features':['log2', 'auto', 'sqrt']}
grid_rf = GridSearchCV(estimator=rf, param_grid=params_df, refit=True,scoring='accuracy', cv=3, n_jobs=-1, verbose=1)
grid_rf.fit(X_train, y_train)
best_hyperparams = grid_rf.best_params_
print('Best hyperparameters \n', best_hyperparams)
#best_model = grid_rf.best_estimator_
#y_pred = best_model.predict(X_test)
#rmse_test = MSE(y_test, y_pred)**(1/2)
#print('Test set RMSE of rf:{:.2f}'.format(rmse_test))
best_cv_score = grid_rf.best_score_
print('Best cv accuracy :{:.3f}'.format(best_cv_score))
best_model = grid_rf.best_estimator_
test_acc = best_model.score(X_test, y_test)
print('Test set accuracy of best model:{:.3f}'.format(test_acc))

Fitting 3 folds for each of 81 candidates, totalling 243 fits
Best hyperparameters
 {'max_depth': 4, 'max_features': 'log2', 'min_samples_leaf': 0.2, 'n_estimators': 400}
Best cv accuracy :0.529
Test set accuracy of best model:0.543

In [49]:
import sys
import warnings
if not sys.warnoptions:
        warnings.simplefilter("ignore")

# MultiLabel XGBoostClassification

In [50]:

import xgboost as xgb
from sklearn.datasets import make_multilabel_classification
from sklearn.model_selection import train_test_split
from sklearn.multioutput import MultiOutputClassifier
from sklearn.metrics import accuracy_score
X = df_new1.values[:, 0:8]
y =df_new1.values[:,8:11]
# create sample dataset
X, y = make_multilabel_classification(n_samples=3000, n_features=45, n_classes=20, n_labels=1,
                                      allow_unlabeled=False, random_state=42)

# split dataset into training and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=123)

# create XGBoost instance with default hyper-parameters
xgb_estimator = xgb.XGBClassifier(objective='binary:logistic', eval_metric='mlogloss')

# create MultiOutputClassifier instance with XGBoost model inside
multilabel_model = MultiOutputClassifier(xgb_estimator)

# fit the model
multilabel_model.fit(X_train, y_train)

# evaluate on test data
print('Accuracy on test data: {:.1f}%'.format(accuracy_score(y_test, multilabel_model.predict(X_test))*100))

Accuracy on test data: 49.8%

# XGBoostClassification using only single column for y_value

In [75]:
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split

X = df_new1.drop(labels='Label', axis=1)
y =df_new1['Label']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=SEED)
model = XGBClassifier()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print(classification_report(y_test, y_pred))
accuracy_score(y_test, y_pred)

[15:20:46] WARNING: /opt/concourse/worker/volumes/live/7a2b9f41-3287-451b-6691-43e9a6c0910f/volume/xgboost-split_1619728204606/work/src/learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
              precision    recall  f1-score   support

           0       0.43      0.32      0.37       260
           1       0.70      0.77      0.73       278
           2       0.46      0.52      0.49       298

    accuracy                           0.54       836
   macro avg       0.53      0.54      0.53       836
weighted avg       0.53      0.54      0.53       836

0.5406698564593302

Did multiLabel classification with decisiontreeclassifier, RandomForestClassifier and XGBoostClassifier. Accuracy scores are a bit low. 
So did preprocessed with LabelEncoder instead one-hot, this improved accuracy by approx 8-9%. 
It is observed that correlation between all the features are pretty close to 1. Except for Rings. Becuase of high correlation accuracy is showing up low.